apiVersion: v1
kind: Namespace
metadata:
  name: security
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitleaks
  namespace: security
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitleaks
  template:
    metadata:
      labels:
        app: gitleaks
    spec:
      containers:
        - name: gitleaks
          image: zricethezav/gitleaks:latest
          command: ["sh", "-c", "sleep infinity"]
